# Generated by Django 4.1.7 on 2023-05-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_fabricacion',
        ),
    ]
