# Generated by Django 4.1.7 on 2023-05-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_producto_fecha_fabricacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nuevo',
        ),
    ]
