# Generated by Django 4.1.6 on 2023-05-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_contacto_avisos_alter_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='tipo_consulta',
        ),
    ]
